#!/bin/bash

CFLAGS=-O2
if [[ $1 == "-p" ]] ; then
  CFLAGS="-prof -auto-all -hisufp_hi -osufp_o -O2"
  shift
fi

if [[ $1 == "-s" ]] ; then
  TARGET=FindOptimal
elif [[ $1 == "-t" ]] ; then
  TARGET=SorterTests
elif [[ $1 == "-f" ]] ; then
  TARGET=FormatDimacs
else
  TARGET=TestCircuits
fi

ghc --make -outputdirbin $CFLAGS $TARGET
