#!/bin/bash

if [[ $1 == "-s" ]] ; then
  ghc --make -outputdirbin -O2 FindOptimal
elif [[ $1 == "-p" ]] ; then
  ghc --make -outputdirbin -prof -auto-all -hisufp_hi -osufp_o SorterTests
else
  ghc --make -outputdirbin -O2 SorterTests
fi
