#!/bin/bash

SATSOLVER_BIN=$1
QUERY_PATH=tmp
LOGFILE=$2

TESTLIST=(`grep -o 'test case: [^.]\+\.' $LOGFILE \
        | sed -r 's/^[^:]+: ([^.]+)./\1/'`)
STATUSLIST=(`grep 'test case: ' $LOGFILE \
        | sed -r 's/^.*Expected: //'`)
n=${#TESTLIST[*]}

for ((i=0;i<n;i++)); do
  test=${TESTLIST[i]}
  status=${STATUSLIST[i]}
  echo "  $test" 
  echo "$test:" >> $LOGFILE
  (time $SATSOLVER_BIN $QUERY_PATH/$test.dimacs) 2>> $LOGFILE \
    | ./FormatDimacs $QUERY_PATH/$test.tmpl > $test.fmtout
  cat $test.fmtout >> $LOGFILE
  head -n 1 $test.fmtout | grep -q "^$status" || echo "    Test failed"
  rm $test.fmtout
done

