#!/bin/bash

GCPARSER_PATH=$1
CIRCUIT_PATH=tmp
LOGFILE=$2

TESTLIST=(`grep -o 'test case: [^.]\+\.' $LOGFILE \
        | sed -r 's/^[^:]+: ([^.]+)./\1/'`)
SUCCESSLIST=(`grep 'test case: ' $LOGFILE \
        | sed -r 's/^.*successVar: //'`)
n=${#TESTLIST[*]}

for ((i=0;i<n;i++)); do
  test=${TESTLIST[i]}
  succ=${SUCCESSLIST[i]}
  echo "$test" 
  echo "$test:" >> $LOGFILE
  DIR=`pwd`
  cd $GCPARSER_PATH
  RDIR=$DIR/makeutils
  # Sometimes this leaves Java processes hanging in the background FIXME
  $RDIR/runopt $DIR/$CIRCUIT_PATH/$test.cir $DIR/$CIRCUIT_PATH/$test-server.in \
               $DIR/$CIRCUIT_PATH/$test-client.in 2>> $DIR/$LOGFILE
  grep -q "$succ = 1" results/siserverout || exit 1
  cd $DIR
done

